### ISSUE TITLE
Slack mkdir error when running from network share

### ISSUE THREAD

**Issue by srliao** [portapps/slack-portable#13]
Got the following error when running slack-portable on a network share. It appears that Slack is calling mkdir on `J:\networkshare` when really `\\networkshare\` is equal to `J:\` as mapped.

Not sure if there's some other env variable slack is looking for? Everything in the log suggests that the paths are correct.

```
Creating Slack Application
INFO : 2018/01/09 23:34:53.338529 main.go:78: --------
INFO : 2018/01/09 23:34:53.346382 main.go:79: Starting Slack...
INFO : 2018/01/09 23:34:53.346382 main.go:80: Current path: J:\Special\IT\Software\slack-portable
INFO : 2018/01/09 23:34:53.347391 main.go:85: Lookup app folder in: J:\Special\IT\Software\slack-portable\app
INFO : 2018/01/09 23:34:53.349394 main.go:89: Electron app folder found: app-3.0.0
INFO : 2018/01/09 23:34:53.350368 main.go:178: Create folder J:\Special\IT\Software\slack-portable\data\AppData\Roaming\Slack...
INFO : 2018/01/09 23:34:53.352370 main.go:25: Roaming path: J:\Special\IT\Software\slack-portable\data\AppData\Roaming\Slack
INFO : 2018/01/09 23:34:53.352370 main.go:178: Create folder J:\Special\IT\Software\slack-portable\downloads...
INFO : 2018/01/09 23:34:53.354365 main.go:35: Update Slack settings...
INFO : 2018/01/09 23:34:53.357374 main.go:42: Current settings:map[locale:en-US spellcheckerLanguage:<nil> versionName:Around The World isBeforeWin10:true launchOnStartup:false runFromTray:true devEnv:<nil> platformVersion:map[build:9600 major:6 minor:3] logFile:<nil> isTitleBarHidden:false isWin10:false whitelistedUrlSchemes:[http: https: mailto: skype: spotify: live: callto: tel: im: sip: sips: slack:] PrefSSBFileDownloadPath:J:\Special\IT\Software\slack-portable\downloads hasRunFromTray:false platform:win32 releaseChannel:prod reportIssueOnStartup:false workspaceIdleTimeout:2.16e+07 autoHideMenuBar:false notifyPosition:map[corner:bottom_right display:same_as_app] notificationPlayback:<nil> openDevToolsOnStart:false windowFlashBehavior:idle appVersion:3.0.0 hasRunApp:true useHwAcceleration:true webappParams:<nil> zoomLevel:0 isAeroGlassEnabled:true pretendNotReallyWindows10:false isTitleBarForcedByUser:false notificationMethod:html resourcePath:J:\Special\IT\Software\slack-portable\app\app-3.0.0\resources\app.asar webappSrcPath:<nil> hasExplainedWindowFlash:false isDevMode:false]
INFO : 2018/01/09 23:34:53.358366 main.go:47: New settings:map[webappSrcPath:<nil> hasExplainedWindowFlash:false isDevMode:false isTitleBarForcedByUser:false notificationMethod:html resourcePath:J:\Special\IT\Software\slack-portable\app\app-3.0.0\resources\app.asar isBeforeWin10:true launchOnStartup:false locale:en-US spellcheckerLanguage:<nil> versionName:Around The World devEnv:<nil> platformVersion:map[minor:3 build:9600 major:6] runFromTray:true logFile:<nil> PrefSSBFileDownloadPath:J:\Special\IT\Software\slack-portable\downloads hasRunFromTray:false isTitleBarHidden:false isWin10:false whitelistedUrlSchemes:[http: https: mailto: skype: spotify: live: callto: tel: im: sip: sips: slack:] workspaceIdleTimeout:2.16e+07 autoHideMenuBar:false notifyPosition:map[corner:bottom_right display:same_as_app] platform:win32 releaseChannel:prod reportIssueOnStartup:false appVersion:3.0.0 hasRunApp:true notificationPlayback:<nil> openDevToolsOnStart:false windowFlashBehavior:idle isAeroGlassEnabled:true pretendNotReallyWindows10:false useHwAcceleration:true webappParams:<nil> zoomLevel:0]
INFO : 2018/01/09 23:34:53.366387 main.go:156: Process: J:\Special\IT\Software\slack-portable\app\Slack.exe
INFO : 2018/01/09 23:34:53.367364 main.go:157: Args: 
INFO : 2018/01/09 23:34:53.371387 main.go:158: Working dir: J:\Special\IT\Software\slack-portable\app\app-3.0.0
INFO : 2018/01/09 23:34:53.372361 main.go:159: Data path: J:\Special\IT\Software\slack-portable\data
INFO : 2018/01/09 23:34:53.374386 main.go:161: Launch Slack...
INFO : 2018/01/09 23:34:53.380395 main.go:168: Exec J:\Special\IT\Software\slack-portable\app\Slack.exe 

{ Error: EPERM: operation not permitted, mkdir 'J:\networkshare'
    at fs.mkdirSync (fs.js:891:18)
    at Object.fs.mkdirSync (ELECTRON_ASAR.js:669:16)
    at mkdirsSync (J:\Special\IT\Software\slack-portable\app\app-3.0.0\resources\app.asar\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:31:9)
    at mkdirsSync (J:\Special\IT\Software\slack-portable\app\app-3.0.0\resources\app.asar\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:37:16)
    at mkdirsSync (J:\Special\IT\Software\slack-portable\app\app-3.0.0\resources\app.asar\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:37:16)
    at mkdirsSync (J:\Special\IT\Software\slack-portable\app\app-3.0.0\resources\app.asar\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:37:16)
    at mkdirsSync (J:\Special\IT\Software\slack-portable\app\app-3.0.0\resources\app.asar\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:37:16)
    at mkdirsSync (J:\Special\IT\Software\slack-portable\app\app-3.0.0\resources\app.asar\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:37:16)
    at Object.mkdirsSync (J:\Special\IT\Software\slack-portable\app\app-3.0.0\resources\app.asar\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:37:16)
    at J:\Special\IT\Software\slack-portable\app\app-3.0.0\resources\app.asar\src\browser\main.ts:188:16
    at Generator.next (<anonymous>)
    at J:\Special\IT\Software\slack-portable\app\app-3.0.0\resources\app.asar\node_modules\tslib\tslib.js:96:75
    at Promise (<anonymous>)
    at Object.__awaiter (J:\Special\IT\Software\slack-portable\app\app-3.0.0\resources\app.asar\node_modules\tslib\tslib.js:92:16)
    at waitForAppReady (J:\Special\IT\Software\slack-portable\app\app-3.0.0\resources\app.asar\src\browser\main.ts:167:20)
    at J:\Special\IT\Software\slack-portable\app\app-3.0.0\resources\app.asar\src\browser\main.ts:379:19
    at Generator.next (<anonymous>)
    at fulfilled (J:\Special\IT\Software\slack-portable\app\app-3.0.0\resources\app.asar\node_modules\tslib\tslib.js:93:62)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
  errno: -4048,
  code: 'EPERM',
  syscall: 'mkdir',
  path: 'J:\\networkshare' }
```

**Comment by crazy-max** [comment]
Hi @srliao, i've never tried to use Slack portable on a network share drive. i will make some test and i keep you in touch.

**Comment by crazy-max** [comment]
I don't have any issue while running slack-portable in a network share drive.
Considering the error, check the permissions on this drive.
